import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "sv";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navbar
    "nav.createEvent": "Create Event",
    "nav.menu": "Menu",
    "nav.manageEvents": "Manage Events",
    "nav.aboutUs": "About Us",
    "nav.contactUs": "Contact Us",
    "nav.signOut": "Sign Out",
    "nav.signIn": "Sign In",
    
    // Hero
    "hero.title1": "Discover Events and Activities",
    "hero.title2": "Across Sweden",
    "hero.subtitle": "Explore thousands of events from Uppsala, Stockholm, and beyond. All in one place.",
    "hero.exploreButton": "Explore Events",
    
    // Events
    "events.title": "Upcoming Events",
    "events.found": "events found",
    "events.noResults": "No events found matching your filters. Try adjusting your search criteria.",
    
    // Footer
    "footer.description": "Discover amazing events and activities across Sweden.",
    "footer.quickLinks": "Quick Links",
    "footer.home": "Home",
    "footer.createEvent": "Create Event",
    "footer.aboutUs": "About Us",
    "footer.contactUs": "Contact Us",
    "footer.dataIntegrity": "Data Integrity",
    "footer.newsletter": "Subscribe to Newsletter",
    "footer.email": "Your email",
    "footer.category": "Category",
    "footer.location": "Location",
    "footer.keywords": "Keywords",
    "footer.any": "Any",
    "footer.optional": "Optional",
    "footer.subscribe": "Subscribe",
    "footer.copyright": "© 2026 NowInTown. All rights reserved.",
    
    // Categories
    "category.all": "Any",
    "category.music": "Music",
    "category.sports": "Sports",
    "category.food": "Food",
    "category.art": "Art",
    "category.tech": "Tech",
    
    // Cookie Consent
    "cookie.title": "We care about your privacy",
    "cookie.description": "We use cookies to improve your browsing experience, show personalized ads or content and analyze our traffic. By clicking \"Accept all\" you consent to our use of cookies.",
    "cookie.customize": "Customize",
    "cookie.rejectAll": "Reject all",
    "cookie.acceptAll": "Accept all",
    
    // Auth
    "auth.invalidEmail": "Invalid email address. Please check and try again.",
    "auth.wrongPassword": "Incorrect password. Please try again or reset your password.",
    "auth.userNotFound": "No account found with this email. Please sign up first.",
    "auth.technicalIssue": "Technical issue occurred. Please contact support@NowInTown.com",
    
    // Create Event
    "create.organizerEmail": "Organizer Email",
    "create.aboutYourself": "About Yourself",
    "create.aboutPlaceholder": "Tell us about yourself and why you want to create this event...",
    "create.pendingApproval": "Your event is pending approval. You'll receive an email confirmation once approved.",
    "create.title": "Create New Event",
    "create.subtitle": "Fill in the details below to publish your event",
    "create.organizerInfo": "Organizer Information",
    "create.organizerInfoDesc": "Tell us about yourself",
    "create.organizerName": "Organizer's Name",
    "create.organizerDesc": "Organizer's Description (Optional)",
    "create.organizerDescPlaceholder": "Tell us about yourself and your experience organizing events (optional)...",
    "create.eventDetails": "Event Details",
    "create.eventDetailsDesc": "Fill in your event information",
    "create.eventTitle": "Event Title",
    "create.eventDesc": "Event Description (Optional)",
    "create.eventDescPlaceholder": "Describe what makes your event special...",
    "create.startDate": "Start Date",
    "create.startTime": "Start Time",
    "create.endDate": "End Date",
    "create.endTime": "End Time",
    "create.location": "Location",
    "create.category": "Category",
    "create.customCategory": "Custom Category",
    "create.eventPrice": "Event Price",
    "create.free": "Free",
    "create.paid": "Paid",
    "create.priceAdults": "Adults",
    "create.priceStudents": "Students",
    "create.priceKids": "Kids",
    "create.priceSeniors": "Seniors",
    "create.eventImage": "Event Image (Optional)",
    "create.uploadImage": "Upload Image",
    "create.changeImage": "Change Image",
    "create.createEvent": "Create Event",
    "create.creatingEvent": "Creating Event...",
    
    // Manage Events
    "manage.title": "Manage Your Events",
    "manage.subtitle": "View and edit your created events",
    "manage.yourEvents": "Your Events",
    "manage.noEvents": "No events yet",
    "manage.noEventsDesc": "You haven't created any events yet. Start by creating your first event!",
    "manage.editDetails": "Edit Event Details",
    "manage.editDetailsDesc": "Update your event information or delete it",
    "manage.statusApproved": "Status: Approved & Published",
    "manage.statusRejected": "Status: Rejected - Contact us if you are interested to know the reason",
    "manage.statusPending": "Status: Approval in Progress",
    "manage.backToList": "Back to List",
    "manage.updateEvent": "Update Event",
    "manage.deleteEvent": "Delete Event",
    "manage.deleteConfirm": "Are you sure?",
    "manage.deleteConfirmDesc": "This action cannot be undone. This will permanently delete your event.",
    "manage.cancel": "Cancel",
    "manage.delete": "Delete",
    
    // Profile
    "profile.title": "My Account",
    "profile.subtitle": "Manage your account settings and preferences",
    "profile.profileInfo": "Profile Information",
    "profile.profileInfoDesc": "View and manage your account details",
    "profile.fullName": "Full Name",
    "profile.email": "Email Address",
    "profile.updatePassword": "Update Password",
    "profile.updatePasswordDesc": "Change your password to keep your account secure",
    "profile.newPassword": "New Password",
    "profile.confirmPassword": "Confirm New Password",
    "profile.changePassword": "Change Password",
    "profile.dangerZone": "Danger Zone",
    "profile.dangerZoneDesc": "Permanently delete your account and all associated data",
    "profile.deleteAccount": "Delete Account",
    "profile.deleteWarning": "This action cannot be undone",
    "profile.deleteConfirm": "Are you absolutely sure?",
    "profile.deleteConfirmDesc": "This will permanently delete your account and all your data. This action cannot be undone.",
    
    // Contact
    "contact.title": "Contact NowInTown",
    "contact.subtitle": "We'd love to hear from you!",
    "contact.description": "Whether you're planning an unforgettable corporate event, a private celebration, or looking to collaborate, the NowInTown team is here to make it happen.",
    "contact.getInTouch": "Get in Touch",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.hours": "Operating Hours",
    "contact.hoursValue": "Monday - Friday: 9:00 AM - 5:00 PM",
    "contact.sendMessage": "Send Us a Message",
    "contact.name": "Name",
    "contact.yourEmail": "Your Email",
    "contact.category": "Category",
    "contact.selectCategory": "Select a category",
    "contact.generalInquiry": "General Inquiry",
    "contact.eventOrganization": "Event Organization",
    "contact.partnership": "Partnership Opportunity",
    "contact.technical": "Technical Support",
    "contact.other": "Other",
    "contact.summary": "Summary",
    "contact.summaryPlaceholder": "Tell us more about your inquiry...",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    
    // Admin Dashboard
    "admin.title": "Admin Dashboard",
    "admin.subtitle": "Manage events and user submissions",
    "admin.pendingEvents": "Pending Events",
    "admin.approvedEvents": "Approved Events",
    "admin.rejectedEvents": "Rejected Events",
    "admin.noEvents": "No events in this category",
    "admin.approve": "Approve",
    "admin.reject": "Reject",
    "admin.view": "View",
    "admin.edit": "Edit",
    "admin.delete": "Delete",
    
    // About Us
    "about.title": "About SwedEvents",
    "about.subtitle": "Connecting people with unforgettable experiences across Sweden",
    "about.mission": "Our Mission",
    "about.missionText1": "NowInTown was born from a simple idea: every amazing event happening across Sweden should be easily discoverable by everyone. Whether it's a local art exhibition in Malmö, a sports tournament in Stockholm, or a music festival in Gothenburg, we believe great experiences should never go unnoticed.",
    "about.missionText2": "We're here to bridge the gap between event organizers and attendees, making it effortless to share, discover, and participate in the vibrant cultural landscape of Sweden.",
    "about.communityTitle": "Community First",
    "about.communitySubtitle": "Building connections that matter",
    "about.communityText": "We believe in the power of community. Every event brings people together, creates memories, and strengthens the social fabric of Sweden.",
    "about.simplicityTitle": "Simplicity & Access",
    "about.simplicitySubtitle": "Easy for everyone to use",
    "about.simplicityText": "Creating and finding events should be simple. Our platform is designed to be intuitive, accessible, and welcoming for all users.",
    "about.qualityTitle": "Quality & Trust",
    "about.qualitySubtitle": "Reliable event information",
    "about.qualityText": "Every event on our platform is reviewed to ensure accuracy and relevance. We're committed to maintaining a trustworthy source of event information.",
    "about.whatWeOfferTitle": "What We Offer",
    "about.organizersTitle": "For Organizers",
    "about.organizersText": "Share your events with thousands of potential attendees across Sweden. Our easy-to-use platform helps you reach the right audience.",
    "about.attendeesTitle": "For Attendees",
    "about.attendeesText": "Discover events tailored to your interests. Filter by category, location, date, and more to find exactly what you're looking for.",
    "about.verificationTitle": "Quality Control",
    "about.verificationText": "All events are reviewed to ensure they meet our quality standards and provide accurate information to our users.",
    "about.storyTitle": "Our Story",
    "about.storyText1": "SwedEvents started in 2024 with a vision to transform how people discover and share events throughout Sweden. Our founders, passionate about community building and cultural experiences, recognized that incredible events were often happening in people's backyards without them knowing.",
    "about.storyText2": "Today, we're proud to serve event organizers and attendees across Sweden, from major cities to small towns. Our platform has become a trusted resource for discovering everything from art exhibitions and sports events to family-friendly activities and professional networking opportunities.",
    "about.storyText3": "We're committed to continuously improving our platform, adding new features, and expanding our reach to ensure that no great event goes undiscovered.",
    "about.coverageTitle": "Nationwide Coverage",
    "about.coverageText": "Events from all across Sweden, from Stockholm to Kiruna",
    "about.updatesTitle": "Daily Updates",
    "about.updatesText": "Fresh event listings added every day by our community",
    "about.communityGrowthTitle": "Growing Community",
    "about.communityGrowthText": "Thousands of event organizers and attendees trust SwedEvents",
    "about.ctaTitle": "Ready to Get Started?",
    "about.ctaText": "Join our community of event organizers and attendees. Create your first event or discover something amazing happening near you.",
    "about.createEvent": "Create an Event",
    "about.exploreEvents": "Explore Events",
    "about.contactTitle": "Get in Touch",
    "about.contactText": "Have questions, suggestions, or just want to say hello? We'd love to hear from you!",
    "about.contactButton": "Contact Us",
  },
  sv: {
    // Navbar
    "nav.createEvent": "Skapa Event",
    "nav.menu": "Meny",
    "nav.manageEvents": "Hantera Event",
    "nav.aboutUs": "Om Oss",
    "nav.contactUs": "Kontakta Oss",
    "nav.signOut": "Logga Ut",
    "nav.signIn": "Logga In",
    
    // Hero
    "hero.title1": "Upptäck Event och Aktiviteter",
    "hero.title2": "Över Hela Sverige",
    "hero.subtitle": "Utforska tusentals evenemang från Uppsala, Stockholm och vidare. Allt på ett ställe.",
    "hero.exploreButton": "Utforska Event",
    
    // Events
    "events.title": "Kommande Event",
    "events.found": "event hittade",
    "events.noResults": "Inga event hittades som matchar dina filter. Prova att justera dina sökkriterier.",
    
    // Footer
    "footer.description": "Upptäck fantastiska event och aktiviteter över hela Sverige.",
    "footer.quickLinks": "Snabblänkar",
    "footer.home": "Hem",
    "footer.createEvent": "Skapa Event",
    "footer.aboutUs": "Om Oss",
    "footer.contactUs": "Kontakta Oss",
    "footer.dataIntegrity": "Dataintegritet",
    "footer.newsletter": "Prenumerera på Nyhetsbrev",
    "footer.email": "Din e-post",
    "footer.category": "Kategori",
    "footer.location": "Plats",
    "footer.keywords": "Nyckelord",
    "footer.any": "Alla",
    "footer.optional": "Valfritt",
    "footer.subscribe": "Prenumerera",
    "footer.copyright": "© 2026 NowInTown. Alla rättigheter förbehållna.",
    
    // Categories
    "category.all": "Alla",
    "category.music": "Musik",
    "category.sports": "Sport",
    "category.food": "Mat",
    "category.art": "Konst",
    "category.tech": "Teknologi",
    
    // Cookie Consent
    "cookie.title": "Vi värnar om din integritet",
    "cookie.description": "Vi använder cookies för att förbättra din surfupplevelse, visa personliga annonser eller innehåll och analysera vår trafik. Genom att klicka på \"Acceptera alla\" samtycker du till vår användning av cookies.",
    "cookie.customize": "Anpassa",
    "cookie.rejectAll": "Avvisa alla",
    "cookie.acceptAll": "Acceptera alla",
    
    // Auth
    "auth.invalidEmail": "Ogiltig e-postadress. Vänligen kontrollera och försök igen.",
    "auth.wrongPassword": "Felaktigt lösenord. Försök igen eller återställ ditt lösenord.",
    "auth.userNotFound": "Inget konto hittades med denna e-post. Vänligen registrera dig först.",
    "auth.technicalIssue": "Tekniskt problem uppstod. Kontakta support@NowInTown.com",
    
    // Create Event
    "create.organizerEmail": "Arrangörs E-post",
    "create.aboutYourself": "Om Dig Själv",
    "create.aboutPlaceholder": "Berätta om dig själv och varför du vill skapa detta event...",
    "create.pendingApproval": "Ditt event väntar på godkännande. Du kommer få en e-postbekräftelse när det godkänts.",
    "create.title": "Skapa Nytt Event",
    "create.subtitle": "Fyll i detaljerna nedan för att publicera ditt event",
    "create.organizerInfo": "Arrangörsinformation",
    "create.organizerInfoDesc": "Berätta om dig själv",
    "create.organizerName": "Arrangörens Namn",
    "create.organizerDesc": "Arrangörens Beskrivning (Valfritt)",
    "create.organizerDescPlaceholder": "Berätta om dig själv och din erfarenhet av att arrangera event (valfritt)...",
    "create.eventDetails": "Eventdetaljer",
    "create.eventDetailsDesc": "Fyll i din eventinformation",
    "create.eventTitle": "Eventtitel",
    "create.eventDesc": "Eventbeskrivning (Valfritt)",
    "create.eventDescPlaceholder": "Beskriv vad som gör ditt event speciellt...",
    "create.startDate": "Startdatum",
    "create.startTime": "Starttid",
    "create.endDate": "Slutdatum",
    "create.endTime": "Sluttid",
    "create.location": "Plats",
    "create.category": "Kategori",
    "create.customCategory": "Egen Kategori",
    "create.eventPrice": "Eventpris",
    "create.free": "Gratis",
    "create.paid": "Betalt",
    "create.priceAdults": "Vuxna",
    "create.priceStudents": "Studenter",
    "create.priceKids": "Barn",
    "create.priceSeniors": "Seniorer",
    "create.eventImage": "Eventbild (Valfritt)",
    "create.uploadImage": "Ladda upp Bild",
    "create.changeImage": "Ändra Bild",
    "create.createEvent": "Skapa Event",
    "create.creatingEvent": "Skapar Event...",
    
    // Manage Events
    "manage.title": "Hantera Dina Event",
    "manage.subtitle": "Visa och redigera dina skapade event",
    "manage.yourEvents": "Dina Event",
    "manage.noEvents": "Inga event ännu",
    "manage.noEventsDesc": "Du har inte skapat några event ännu. Börja med att skapa ditt första event!",
    "manage.editDetails": "Redigera Eventdetaljer",
    "manage.editDetailsDesc": "Uppdatera din eventinformation eller radera den",
    "manage.statusApproved": "Status: Godkänt & Publicerat",
    "manage.statusRejected": "Status: Avvisat - Kontakta oss om du vill veta varför",
    "manage.statusPending": "Status: Väntar på Godkännande",
    "manage.backToList": "Tillbaka till Listan",
    "manage.updateEvent": "Uppdatera Event",
    "manage.deleteEvent": "Radera Event",
    "manage.deleteConfirm": "Är du säker?",
    "manage.deleteConfirmDesc": "Denna åtgärd kan inte ångras. Detta kommer permanent radera ditt event.",
    "manage.cancel": "Avbryt",
    "manage.delete": "Radera",
    
    // Profile
    "profile.title": "Mitt Konto",
    "profile.subtitle": "Hantera dina kontoinställningar och preferenser",
    "profile.profileInfo": "Profilinformation",
    "profile.profileInfoDesc": "Visa och hantera dina kontodetaljer",
    "profile.fullName": "Fullständigt Namn",
    "profile.email": "E-postadress",
    "profile.updatePassword": "Uppdatera Lösenord",
    "profile.updatePasswordDesc": "Ändra ditt lösenord för att hålla ditt konto säkert",
    "profile.newPassword": "Nytt Lösenord",
    "profile.confirmPassword": "Bekräfta Nytt Lösenord",
    "profile.changePassword": "Ändra Lösenord",
    "profile.dangerZone": "Farlig Zon",
    "profile.dangerZoneDesc": "Radera permanent ditt konto och all associerad data",
    "profile.deleteAccount": "Radera Konto",
    "profile.deleteWarning": "Denna åtgärd kan inte ångras",
    "profile.deleteConfirm": "Är du helt säker?",
    "profile.deleteConfirmDesc": "Detta kommer permanent radera ditt konto och all din data. Denna åtgärd kan inte ångras.",
    
    // Contact
    "contact.title": "Kontakta NowInTown",
    "contact.subtitle": "Vi vill gärna höra från dig!",
    "contact.description": "Oavsett om du planerar ett minnesvärt företagsevent, en privat fest eller vill samarbeta, är NowInTown-teamet här för att göra det möjligt.",
    "contact.getInTouch": "Kom i Kontakt",
    "contact.email": "E-post",
    "contact.phone": "Telefon",
    "contact.hours": "Öppettider",
    "contact.hoursValue": "Måndag - Fredag: 09:00 - 17:00",
    "contact.sendMessage": "Skicka Meddelande",
    "contact.name": "Namn",
    "contact.yourEmail": "Din E-post",
    "contact.category": "Kategori",
    "contact.selectCategory": "Välj en kategori",
    "contact.generalInquiry": "Allmän Förfrågan",
    "contact.eventOrganization": "Eventorganisation",
    "contact.partnership": "Partnerskapsmöjlighet",
    "contact.technical": "Teknisk Support",
    "contact.other": "Annat",
    "contact.summary": "Sammanfattning",
    "contact.summaryPlaceholder": "Berätta mer om din förfrågan...",
    "contact.send": "Skicka Meddelande",
    "contact.sending": "Skickar...",
    
    // Admin Dashboard
    "admin.title": "Admin Panel",
    "admin.subtitle": "Hantera event och användarinlämningar",
    "admin.pendingEvents": "Väntande Event",
    "admin.approvedEvents": "Godkända Event",
    "admin.rejectedEvents": "Avvisade Event",
    "admin.noEvents": "Inga event i denna kategori",
    "admin.approve": "Godkänn",
    "admin.reject": "Avvisa",
    "admin.view": "Visa",
    "admin.edit": "Redigera",
    "admin.delete": "Radera",
    
    // About Us
    "about.title": "Om SwedEvents",
    "about.subtitle": "Kopplar samman människor med oförglömliga upplevelser över hela Sverige",
    "about.mission": "Vårt Uppdrag",
    "about.missionText1": "NowInTown föddes från en enkel idé: varje fantastiskt evenemang som händer över hela Sverige borde vara lätt att upptäcka för alla. Oavsett om det är en lokal konstutställning i Malmö, en sportturnering i Stockholm eller en musikfestival i Göteborg, tror vi att fantastiska upplevelser aldrig ska gå obemärkt förbi.",
    "about.missionText2": "Vi är här för att överbrygga klyftan mellan eventarrangörer och deltagare, vilket gör det enkelt att dela, upptäcka och delta i Sveriges livliga kulturella landskap.",
    "about.communityTitle": "Gemenskap Först",
    "about.communitySubtitle": "Bygga kontakter som betyder något",
    "about.communityText": "Vi tror på gemenskapens kraft. Varje evenemang för människor samman, skapar minnen och stärker Sveriges sociala struktur.",
    "about.simplicityTitle": "Enkelhet & Tillgång",
    "about.simplicitySubtitle": "Lätt för alla att använda",
    "about.simplicityText": "Att skapa och hitta evenemang ska vara enkelt. Vår plattform är designad för att vara intuitiv, tillgänglig och välkomnande för alla användare.",
    "about.qualityTitle": "Kvalitet & Förtroende",
    "about.qualitySubtitle": "Tillförlitlig eventinformation",
    "about.qualityText": "Varje evenemang på vår plattform granskas för att säkerställa noggrannhet och relevans. Vi är engagerade i att upprätthålla en pålitlig källa för eventinformation.",
    "about.whatWeOfferTitle": "Vad Vi Erbjuder",
    "about.organizersTitle": "För Arrangörer",
    "about.organizersText": "Dela dina evenemang med tusentals potentiella deltagare över hela Sverige. Vår lättanvända plattform hjälper dig att nå rätt publik.",
    "about.attendeesTitle": "För Deltagare",
    "about.attendeesText": "Upptäck evenemang anpassade efter dina intressen. Filtrera efter kategori, plats, datum och mer för att hitta exakt vad du letar efter.",
    "about.verificationTitle": "Kvalitetskontroll",
    "about.verificationText": "Alla evenemang granskas för att säkerställa att de uppfyller våra kvalitetsstandarder och ger korrekt information till våra användare.",
    "about.storyTitle": "Vår Historia",
    "about.storyText1": "SwedEvents startade 2024 med en vision att förändra hur människor upptäcker och delar evenemang över hela Sverige. Våra grundare, passionerade för att bygga gemenskap och kulturella upplevelser, insåg att otroliga evenemang ofta hände i människors trädgårdar utan att de visste om det.",
    "about.storyText2": "Idag är vi stolta över att tjäna eventarrangörer och deltagare över hela Sverige, från stora städer till små städer. Vår plattform har blivit en pålitlig resurs för att upptäcka allt från konstutställningar och sportevenemang till familjevänliga aktiviteter och professionella nätverksmöjligheter.",
    "about.storyText3": "Vi är engagerade i att kontinuerligt förbättra vår plattform, lägga till nya funktioner och utöka vår räckvidd för att säkerställa att inget fantastiskt evenemang förblir oupptäckt.",
    "about.coverageTitle": "Rikstäckning",
    "about.coverageText": "Evenemang från hela Sverige, från Stockholm till Kiruna",
    "about.updatesTitle": "Dagliga Uppdateringar",
    "about.updatesText": "Nya eventlistor läggs till varje dag av vår gemenskap",
    "about.communityGrowthTitle": "Växande Gemenskap",
    "about.communityGrowthText": "Tusentals eventarrangörer och deltagare litar på SwedEvents",
    "about.ctaTitle": "Redo att Komma Igång?",
    "about.ctaText": "Gå med i vår gemenskap av eventarrangörer och deltagare. Skapa ditt första evenemang eller upptäck något fantastiskt som händer nära dig.",
    "about.createEvent": "Skapa ett Evenemang",
    "about.exploreEvents": "Utforska Evenemang",
    "about.contactTitle": "Kom i Kontakt",
    "about.contactText": "Har du frågor, förslag eller vill bara säga hej? Vi vill gärna höra från dig!",
    "about.contactButton": "Kontakta Oss",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("sv");

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
