import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "sv";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navbar
    "nav.createEvent": "Create Event",
    "nav.menu": "Menu",
    "nav.manageEvents": "Manage Events",
    "nav.aboutUs": "About Us",
    "nav.contactUs": "Contact Us",
    "nav.signOut": "Sign Out",
    "nav.signIn": "Sign In",
    
    // Hero
    "hero.title1": "Discover Events and Activities",
    "hero.title2": "Across Sweden",
    "hero.subtitle": "Explore thousands of events from Uppsala, Stockholm, and beyond. All in one place.",
    "hero.exploreButton": "Explore Events",
    
    // Events
    "events.title": "Upcoming Events",
    "events.found": "events found",
    "events.noResults": "No events found matching your filters. Try adjusting your search criteria.",
    
    // Footer
    "footer.description": "Discover amazing events and activities across Sweden.",
    "footer.quickLinks": "Quick Links",
    "footer.home": "Home",
    "footer.createEvent": "Create Event",
    "footer.aboutUs": "About Us",
    "footer.contactUs": "Contact Us",
    "footer.dataIntegrity": "Data Integrity",
    "footer.terms": "Terms & Conditions",
    "footer.newsletter": "Subscribe to Newsletter",
    "footer.email": "Your email",
    "footer.category": "Category",
    "footer.location": "Location",
    "footer.keywords": "Keywords",
    "footer.any": "Any",
    "footer.optional": "Optional",
    "footer.subscribe": "Subscribe",
    "footer.copyright": "© 2026 NowInTown. All rights reserved.",
    
    // Categories
    "category.all": "Any",
    "category.music": "Music",
    "category.sports": "Sports",
    "category.food": "Food",
    "category.art": "Art",
    "category.tech": "Tech",
    
    // Cookie Consent
    "cookie.title": "We care about your privacy",
    "cookie.description": "We use cookies to improve your browsing experience and analyze our traffic. By clicking \"Accept all\" you consent to our use of all cookies. Click \"Accept necessary\" to only allow essential cookies required for the website to function.",
    "cookie.acceptNecessary": "Accept Necessary",
    "cookie.acceptAll": "Accept All",
    
    // Auth
    "auth.invalidEmail": "Invalid email address. Please check and try again.",
    "auth.wrongPassword": "Incorrect password. Please try again or reset your password.",
    "auth.userNotFound": "No account found with this email. Please sign up first.",
    "auth.technicalIssue": "Technical issue occurred. Please contact support@NowInTown.com",
    
    // Create Event
    "create.organizerEmail": "Organizer Email",
    "create.aboutYourself": "About Yourself",
    "create.aboutPlaceholder": "Tell us about yourself and why you want to create this event...",
    "create.pendingApproval": "Your event is pending approval. You'll receive an email confirmation once approved.",
    "create.title": "Create New Event",
    "create.subtitle": "Fill in the details below to publish your event",
    "create.organizerInfo": "Organizer Information",
    "create.organizerInfoDesc": "Tell us about yourself",
    "create.organizerName": "Organizer's Name",
    "create.organizerDesc": "Organizer's Description (Optional)",
    "create.organizerDescPlaceholder": "Tell us about yourself and your experience organizing events (optional)...",
    "create.eventDetails": "Event Details",
    "create.eventDetailsDesc": "Fill in your event information",
    "create.eventTitle": "Event Title",
    "create.eventDesc": "Event Description",
    "create.eventDescPlaceholder": "Describe what makes your event special...",
    "create.startDate": "Start Date",
    "create.startTime": "Start Time",
    "create.endDate": "End Date",
    "create.endTime": "End Time",
    "create.location": "Location",
    "create.category": "Category",
    "create.customCategory": "Custom Category",
    "create.eventPrice": "Event Price",
    "create.free": "Free",
    "create.paid": "Paid",
    "create.priceAdults": "Adults",
    "create.priceStudents": "Students",
    "create.priceKids": "Kids",
    "create.priceSeniors": "Seniors",
    "create.eventImage": "Event Image (Optional)",
    "create.uploadImage": "Upload Image",
    "create.changeImage": "Change Image",
    "create.createEvent": "Create Event",
    "create.creatingEvent": "Creating Event...",
    
    // Manage Events
    "manage.title": "Manage Your Events",
    "manage.subtitle": "View and edit your created events",
    "manage.yourEvents": "Your Events",
    "manage.noEvents": "No events yet",
    "manage.noEventsDesc": "You haven't created any events yet. Start by creating your first event!",
    "manage.editDetails": "Edit Event Details",
    "manage.editDetailsDesc": "Update your event information or delete it",
    "manage.statusApproved": "Status: Approved & Published",
    "manage.statusRejected": "Status: Rejected - Contact us if you are interested to know the reason",
    "manage.statusPending": "Status: Approval in Progress",
    "manage.backToList": "Back to List",
    "manage.updateEvent": "Update Event",
    "manage.deleteEvent": "Delete Event",
    "manage.deleteConfirm": "Are you sure?",
    "manage.deleteConfirmDesc": "This action cannot be undone. This will permanently delete your event.",
    "manage.cancel": "Cancel",
    "manage.delete": "Delete",
    
    // Profile
    "profile.title": "My Account",
    "profile.subtitle": "Manage your account settings and preferences",
    "profile.profileInfo": "Profile Information",
    "profile.profileInfoDesc": "View and manage your account details",
    "profile.fullName": "Full Name",
    "profile.email": "Email Address",
    "profile.updatePassword": "Update Password",
    "profile.updatePasswordDesc": "Change your password to keep your account secure",
    "profile.newPassword": "New Password",
    "profile.confirmPassword": "Confirm New Password",
    "profile.changePassword": "Change Password",
    "profile.dangerZone": "Danger Zone",
    "profile.dangerZoneDesc": "Permanently delete your account and all associated data",
    "profile.deleteAccount": "Delete Account",
    "profile.deleteWarning": "This action cannot be undone",
    "profile.deleteConfirm": "Are you absolutely sure?",
    "profile.deleteConfirmDesc": "This will permanently delete your account and all your data. This action cannot be undone.",
    
    // Contact
    "contact.title": "Contact NowInTown",
    "contact.subtitle": "We'd love to hear from you!",
    "contact.description": "Whether you're planning an unforgettable corporate event, a private celebration, or looking to collaborate, the NowInTown team is here to make it happen.",
    "contact.getInTouch": "Get in Touch",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.hours": "Operating Hours",
    "contact.hoursValue": "Monday - Friday: 9:00 AM - 5:00 PM",
    "contact.sendMessage": "Send Us a Message",
    "contact.name": "Name",
    "contact.yourEmail": "Your Email",
    "contact.category": "Category",
    "contact.selectCategory": "Select a category",
    "contact.generalInquiry": "General Inquiry",
    "contact.eventOrganization": "Event Organization",
    "contact.partnership": "Partnership Opportunity",
    "contact.technical": "Technical Support",
    "contact.other": "Other",
    "contact.summary": "Summary",
    "contact.summaryPlaceholder": "Tell us more about your inquiry...",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    
    // Admin Dashboard
    "admin.title": "Admin Dashboard",
    "admin.subtitle": "Manage events and user submissions",
    "admin.pendingEvents": "Pending Events",
    "admin.approvedEvents": "Approved Events",
    "admin.rejectedEvents": "Rejected Events",
    "admin.noEvents": "No events in this category",
    "admin.approve": "Approve",
    "admin.reject": "Reject",
    "admin.view": "View",
    "admin.edit": "Edit",
    "admin.delete": "Delete",
    
    // About Us
    "aboutUs.pageTitle": "About NowInTown - Breaking Loneliness Through Social Events",
    "aboutUs.pageDescription": "Discover NowInTown: Breaking loneliness and bringing people together through events. Our mission is to help you enjoy social life and have fun with others.",
    "aboutUs.title": "About NowInTown",
    "aboutUs.subtitle": "Breaking loneliness, building connections, one event at a time",
    "aboutUs.heroImageAlt": "People enjoying social connections together",
    "aboutUs.mission": "Our Mission",
    "aboutUs.missionText1": "At NowInTown, our main goal and ambition is to break loneliness and bring people together to have fun and enjoy social life. We believe that meaningful connections happen when people gather for events they love.",
    "aboutUs.missionText2": "Whether you're looking for cultural events, sports activities, concerts, or community gatherings, we make it easy to discover and attend events that matter to you. Every event is an opportunity to meet new people, create memories, and strengthen your social connections.",
    "aboutUs.valueTitle1": "Community First",
    "aboutUs.valueSubtitle1": "Building connections that matter",
    "aboutUs.valueText1": "We believe in the power of community. Every event brings people together, creates memories, and strengthens social bonds. Our platform is designed to break loneliness and foster meaningful connections.",
    "aboutUs.valueTitle2": "Simplicity & Access",
    "aboutUs.valueSubtitle2": "Easy for everyone to use",
    "aboutUs.valueText2": "Creating and finding events should be simple. Our platform is designed to be intuitive, accessible, and welcoming for all users who want to enjoy social life.",
    "aboutUs.valueTitle3": "Quality & Trust",
    "aboutUs.valueSubtitle3": "Reliable event information",
    "aboutUs.valueText3": "We maintain high standards for event listings and protect user data with enterprise-grade security measures.",
    "about.title": "About NowInTown",
    "about.communityTitle": "Community First",
    "about.communitySubtitle": "Building connections that matter",
    "about.communityText": "We believe in the power of community. Every event brings people together, creates memories, and strengthens the social fabric of Sweden.",
    "about.simplicityTitle": "Simplicity & Access",
    "about.simplicitySubtitle": "Easy for everyone to use",
    "about.simplicityText": "Creating and finding events should be simple. Our platform is designed to be intuitive, accessible, and welcoming for all users.",
    "about.qualityTitle": "Quality & Trust",
    "about.qualitySubtitle": "Reliable event information",
    "about.qualityText": "Every event on our platform is reviewed to ensure accuracy and relevance. We're committed to maintaining a trustworthy source of event information.",
    "about.whatWeOfferTitle": "What We Offer",
    "about.organizersTitle": "For Organizers",
    "about.organizersText": "Share your events with thousands of potential attendees across Sweden. Our easy-to-use platform helps you reach the right audience.",
    "about.attendeesTitle": "For Attendees",
    "about.attendeesText": "Discover events tailored to your interests. Filter by category, location, date, and more to find exactly what you're looking for.",
    "about.verificationTitle": "Quality Control",
    "about.verificationText": "All events are reviewed to ensure they meet our quality standards and provide accurate information to our users.",
    "about.storyTitle": "Our Story",
    "about.storyText1": "NowInTown started in 2025 with a vision to transform how people discover and share events throughout Sweden. Our founders, passionate about community building and cultural experiences, recognized that incredible events were often happening in people's backyards without them knowing.",
    "about.storyText2": "Today, we're proud to serve event organizers and attendees across Sweden, from major cities to small towns. Our platform has become a trusted resource for discovering everything from art exhibitions and sports events to family-friendly activities and professional networking opportunities.",
    "about.storyText3": "We're committed to continuously improving our platform, adding new features, and expanding our reach to ensure that no great event goes undiscovered.",
    "about.coverageTitle": "Nationwide Coverage",
    "about.coverageText": "Events from all across Sweden, from Stockholm to Kiruna",
    "about.updatesTitle": "Daily Updates",
    "about.updatesText": "Fresh event listings added every day by our community",
    "about.communityGrowthTitle": "Growing Community",
    "about.communityGrowthText": "Thousands of event organizers and attendees trust NowInTown",
    "about.ctaTitle": "Ready to Get Started?",
    "about.ctaText": "Join our community of event organizers and attendees. Create your first event or discover something amazing happening near you.",
    "about.createEvent": "Create an Event",
    "about.exploreEvents": "Explore Events",
    "about.contactTitle": "Get in Touch",
    "about.contactText": "Have questions, suggestions, or just want to say hello? We'd love to hear from you!",
    "about.contactButton": "Contact Us",
    
    // Data Integrity
    "dataIntegrity.pageTitle": "Data Integrity & Security - NowInTown | Secure Event Management",
    "dataIntegrity.pageDescription": "Learn how NowInTown ensures data integrity and security for all event information. Our commitment to protecting your data with enterprise-grade security measures.",
    "dataIntegrity.title": "Data Integrity & Security",
    "dataIntegrity.subtitle": "Your trust is our priority. We implement robust security measures to protect your event data and ensure its integrity at all times.",
    "dataIntegrity.dataProtection": "Data Protection",
    "dataIntegrity.dataProtectionDesc": "Enterprise-grade security for your peace of mind",
    "dataIntegrity.dataProtectionText": "All event data is encrypted both in transit and at rest using industry-standard encryption protocols. We employ SSL/TLS certificates and secure data transmission to protect your information from unauthorized access.",
    "dataIntegrity.accessControl": "Access Control",
    "dataIntegrity.accessControlDesc": "Secure authentication and authorization",
    "dataIntegrity.accessControlText1": "Event organizers receive unique access codes to manage their events. Only authorized users can view, modify, or delete event information, ensuring complete control over your data.",
    "dataIntegrity.accessControlText2": "Users can manage their account settings, reset passwords, and delete their accounts at any time through their",
    "dataIntegrity.accountPage": "account page",
    "dataIntegrity.dataIntegrity": "Data Integrity",
    "dataIntegrity.dataIntegrityDesc": "Reliable and consistent information",
    "dataIntegrity.dataIntegrityText": "We maintain strict data validation rules to ensure all event information remains accurate and consistent. Regular integrity checks prevent data corruption and maintain reliability across our platform.",
    "dataIntegrity.autoCleanup": "Automatic Cleanup",
    "dataIntegrity.autoCleanupDesc": "Privacy-first data management",
    "dataIntegrity.autoCleanupText": "Events are automatically deleted at the end of their scheduled date, ensuring no unnecessary data retention. This privacy-first approach minimizes data storage and protects user information.",
    "dataIntegrity.transparency": "Transparency",
    "dataIntegrity.transparencyDesc": "Clear data usage policies",
    "dataIntegrity.transparencyText": "We collect only essential information needed to display and manage events. No personal data is shared with third parties without explicit consent, and users can request data deletion at any time.",
    "dataIntegrity.regularBackups": "Regular Backups",
    "dataIntegrity.regularBackupsDesc": "Reliable data recovery",
    "dataIntegrity.regularBackupsText": "Automated backups ensure your event data is safe and recoverable in case of system failures. Our redundant storage systems guarantee high availability and data durability.",
    "dataIntegrity.commitmentTitle": "Our Commitment to You",
    "dataIntegrity.commitmentText": "At NowInTown, we understand that your event data is valuable and sensitive. We are committed to maintaining the highest standards of data security and integrity through:",
    "dataIntegrity.commitmentItem1": "Regular security audits and penetration testing",
    "dataIntegrity.commitmentItem2": "Compliance with GDPR and international data protection regulations",
    "dataIntegrity.commitmentItem3": "Continuous monitoring for suspicious activities",
    "dataIntegrity.commitmentItem4": "Prompt security updates and patches",
    "dataIntegrity.commitmentItem5": "Transparent incident reporting and response procedures",
    "dataIntegrity.contactText": "If you have any questions about our data security practices or would like to report a security concern, please",
    "dataIntegrity.contactUs": "contact us",
    "dataIntegrity.manageAccountTitle": "Manage Your Account",
    "dataIntegrity.manageAccountText": "Take full control of your account settings, update your password, or delete your account at any time.",
    "dataIntegrity.goToAccount": "Go to My Account",
  },
  sv: {
    // Navbar
    "nav.createEvent": "Skapa Event",
    "nav.menu": "Meny",
    "nav.manageEvents": "Hantera Event",
    "nav.aboutUs": "Om Oss",
    "nav.contactUs": "Kontakta Oss",
    "nav.signOut": "Logga Ut",
    "nav.signIn": "Logga In",
    
    // Hero
    "hero.title1": "Upptäck Event och Aktiviteter",
    "hero.title2": "Över Hela Sverige",
    "hero.subtitle": "Utforska tusentals evenemang från Uppsala, Stockholm och vidare. Allt på ett ställe.",
    "hero.exploreButton": "Utforska Event",
    
    // Events
    "events.title": "Kommande Event",
    "events.found": "event hittade",
    "events.noResults": "Inga event hittades som matchar dina filter. Prova att justera dina sökkriterier.",
    
    // Footer
    "footer.description": "Upptäck fantastiska event och aktiviteter över hela Sverige.",
    "footer.quickLinks": "Snabblänkar",
    "footer.home": "Hem",
    "footer.createEvent": "Skapa Event",
    "footer.aboutUs": "Om Oss",
    "footer.contactUs": "Kontakta Oss",
    "footer.dataIntegrity": "Dataintegritet",
    "footer.terms": "Villkor",
    "footer.newsletter": "Prenumerera på Nyhetsbrev",
    "footer.email": "Din e-post",
    "footer.category": "Kategori",
    "footer.location": "Plats",
    "footer.keywords": "Nyckelord",
    "footer.any": "Alla",
    "footer.optional": "Valfritt",
    "footer.subscribe": "Prenumerera",
    "footer.copyright": "© 2026 NowInTown. Alla rättigheter förbehållna.",
    
    // Categories
    "category.all": "Alla",
    "category.music": "Musik",
    "category.sports": "Sport",
    "category.food": "Mat",
    "category.art": "Konst",
    "category.tech": "Teknologi",
    
    // Cookie Consent
    "cookie.title": "Vi värnar om din integritet",
    "cookie.description": "Vi använder cookies för att förbättra din surfupplevelse och analysera vår trafik. Genom att klicka på \"Acceptera alla\" samtycker du till vår användning av alla cookies. Klicka på \"Acceptera nödvändiga\" för att endast tillåta nödvändiga cookies.",
    "cookie.acceptNecessary": "Acceptera Nödvändiga",
    "cookie.acceptAll": "Acceptera Alla",
    
    // Auth
    "auth.invalidEmail": "Ogiltig e-postadress. Vänligen kontrollera och försök igen.",
    "auth.wrongPassword": "Felaktigt lösenord. Försök igen eller återställ ditt lösenord.",
    "auth.userNotFound": "Inget konto hittades med denna e-post. Vänligen registrera dig först.",
    "auth.technicalIssue": "Tekniskt problem uppstod. Kontakta support@NowInTown.com",
    
    // Create Event
    "create.organizerEmail": "Arrangörs E-post",
    "create.aboutYourself": "Om Dig Själv",
    "create.aboutPlaceholder": "Berätta om dig själv och varför du vill skapa detta event...",
    "create.pendingApproval": "Ditt event väntar på godkännande. Du kommer få en e-postbekräftelse när det godkänts.",
    "create.title": "Skapa Nytt Event",
    "create.subtitle": "Fyll i detaljerna nedan för att publicera ditt event",
    "create.organizerInfo": "Arrangörsinformation",
    "create.organizerInfoDesc": "Berätta om dig själv",
    "create.organizerName": "Arrangörens Namn",
    "create.organizerDesc": "Arrangörens Beskrivning (Valfritt)",
    "create.organizerDescPlaceholder": "Berätta om dig själv och din erfarenhet av att arrangera event (valfritt)...",
    "create.eventDetails": "Eventdetaljer",
    "create.eventDetailsDesc": "Fyll i din eventinformation",
    "create.eventTitle": "Eventtitel",
    "create.eventDesc": "Eventbeskrivning",
    "create.eventDescPlaceholder": "Beskriv vad som gör ditt event speciellt...",
    "create.startDate": "Startdatum",
    "create.startTime": "Starttid",
    "create.endDate": "Slutdatum",
    "create.endTime": "Sluttid",
    "create.location": "Plats",
    "create.category": "Kategori",
    "create.customCategory": "Egen Kategori",
    "create.eventPrice": "Eventpris",
    "create.free": "Gratis",
    "create.paid": "Betalt",
    "create.priceAdults": "Vuxna",
    "create.priceStudents": "Studenter",
    "create.priceKids": "Barn",
    "create.priceSeniors": "Seniorer",
    "create.eventImage": "Eventbild (Valfritt)",
    "create.uploadImage": "Ladda upp Bild",
    "create.changeImage": "Ändra Bild",
    "create.createEvent": "Skapa Event",
    "create.creatingEvent": "Skapar Event...",
    
    // Manage Events
    "manage.title": "Hantera Dina Event",
    "manage.subtitle": "Visa och redigera dina skapade event",
    "manage.yourEvents": "Dina Event",
    "manage.noEvents": "Inga event ännu",
    "manage.noEventsDesc": "Du har inte skapat några event ännu. Börja med att skapa ditt första event!",
    "manage.editDetails": "Redigera Eventdetaljer",
    "manage.editDetailsDesc": "Uppdatera din eventinformation eller radera den",
    "manage.statusApproved": "Status: Godkänt & Publicerat",
    "manage.statusRejected": "Status: Avvisat - Kontakta oss om du vill veta varför",
    "manage.statusPending": "Status: Väntar på Godkännande",
    "manage.backToList": "Tillbaka till Listan",
    "manage.updateEvent": "Uppdatera Event",
    "manage.deleteEvent": "Radera Event",
    "manage.deleteConfirm": "Är du säker?",
    "manage.deleteConfirmDesc": "Denna åtgärd kan inte ångras. Detta kommer permanent radera ditt event.",
    "manage.cancel": "Avbryt",
    "manage.delete": "Radera",
    
    // Profile
    "profile.title": "Mitt Konto",
    "profile.subtitle": "Hantera dina kontoinställningar och preferenser",
    "profile.profileInfo": "Profilinformation",
    "profile.profileInfoDesc": "Visa och hantera dina kontodetaljer",
    "profile.fullName": "Fullständigt Namn",
    "profile.email": "E-postadress",
    "profile.updatePassword": "Uppdatera Lösenord",
    "profile.updatePasswordDesc": "Ändra ditt lösenord för att hålla ditt konto säkert",
    "profile.newPassword": "Nytt Lösenord",
    "profile.confirmPassword": "Bekräfta Nytt Lösenord",
    "profile.changePassword": "Ändra Lösenord",
    "profile.dangerZone": "Farlig Zon",
    "profile.dangerZoneDesc": "Radera permanent ditt konto och all associerad data",
    "profile.deleteAccount": "Radera Konto",
    "profile.deleteWarning": "Denna åtgärd kan inte ångras",
    "profile.deleteConfirm": "Är du helt säker?",
    "profile.deleteConfirmDesc": "Detta kommer permanent radera ditt konto och all din data. Denna åtgärd kan inte ångras.",
    
    // Contact
    "contact.title": "Kontakta NowInTown",
    "contact.subtitle": "Vi vill gärna höra från dig!",
    "contact.description": "Oavsett om du planerar ett minnesvärt företagsevent, en privat fest eller vill samarbeta, är NowInTown-teamet här för att göra det möjligt.",
    "contact.getInTouch": "Kom i Kontakt",
    "contact.email": "E-post",
    "contact.phone": "Telefon",
    "contact.hours": "Öppettider",
    "contact.hoursValue": "Måndag - Fredag: 09:00 - 17:00",
    "contact.sendMessage": "Skicka Meddelande",
    "contact.name": "Namn",
    "contact.yourEmail": "Din E-post",
    "contact.category": "Kategori",
    "contact.selectCategory": "Välj en kategori",
    "contact.generalInquiry": "Allmän Förfrågan",
    "contact.eventOrganization": "Eventorganisation",
    "contact.partnership": "Partnerskapsmöjlighet",
    "contact.technical": "Teknisk Support",
    "contact.other": "Annat",
    "contact.summary": "Sammanfattning",
    "contact.summaryPlaceholder": "Berätta mer om din förfrågan...",
    "contact.send": "Skicka Meddelande",
    "contact.sending": "Skickar...",
    
    // Admin Dashboard
    "admin.title": "Admin Panel",
    "admin.subtitle": "Hantera event och användarinlämningar",
    "admin.pendingEvents": "Väntande Event",
    "admin.approvedEvents": "Godkända Event",
    "admin.rejectedEvents": "Avvisade Event",
    "admin.noEvents": "Inga event i denna kategori",
    "admin.approve": "Godkänn",
    "admin.reject": "Avvisa",
    "admin.view": "Visa",
    "admin.edit": "Redigera",
    "admin.delete": "Radera",
    
    // About Us
    "aboutUs.pageTitle": "Om NowInTown - Bryta Ensamhet Genom Sociala Event",
    "aboutUs.pageDescription": "Upptäck NowInTown: Bryta ensamhet och föra människor samman genom evenemang. Vår mission är att hjälpa dig njuta av det sociala livet och ha kul med andra.",
    "aboutUs.title": "Om NowInTown",
    "aboutUs.subtitle": "Bryta ensamhet, bygga relationer, ett evenemang i taget",
    "aboutUs.heroImageAlt": "Personer som njuter av sociala kontakter tillsammans",
    "aboutUs.mission": "Vårt Uppdrag",
    "aboutUs.missionText1": "På NowInTown är vårt huvudmål och ambition att bryta ensamhet och föra människor samman för att ha kul och njuta av det sociala livet. Vi tror att meningsfulla kontakter uppstår när människor samlas för evenemang de älskar.",
    "aboutUs.missionText2": "Oavsett om du letar efter kulturevenemang, sportaktiviteter, konserter eller samhällsträffar, gör vi det enkelt att upptäcka och delta i evenemang som betyder något för dig. Varje evenemang är en möjlighet att träffa nya människor, skapa minnen och stärka dina sociala kontakter.",
    "aboutUs.valueTitle1": "Gemenskap Först",
    "aboutUs.valueSubtitle1": "Bygga kontakter som betyder något",
    "aboutUs.valueText1": "Vi tror på gemenskapens kraft. Varje evenemang för människor samman, skapar minnen och stärker sociala band. Vår plattform är designad för att bryta ensamhet och främja meningsfulla kontakter.",
    "aboutUs.valueTitle2": "Enkelhet & Tillgång",
    "aboutUs.valueSubtitle2": "Lätt för alla att använda",
    "aboutUs.valueText2": "Att skapa och hitta evenemang ska vara enkelt. Vår plattform är designad för att vara intuitiv, tillgänglig och välkomnande för alla användare som vill njuta av det sociala livet.",
    "aboutUs.valueTitle3": "Kvalitet & Förtroende",
    "aboutUs.valueSubtitle3": "Tillförlitlig evenemangsinformation",
    "aboutUs.valueText3": "Vi upprätthåller höga standarder för evenemangslistor och skyddar användardata med säkerhetsåtgärder i företagsklass.",
    "about.title": "Om NowInTown",
    "about.communityTitle": "Gemenskap Först",
    "about.communitySubtitle": "Bygga kontakter som betyder något",
    "about.communityText": "Vi tror på gemenskapens kraft. Varje evenemang för människor samman, skapar minnen och stärker Sveriges sociala struktur.",
    "about.simplicityTitle": "Enkelhet & Tillgång",
    "about.simplicitySubtitle": "Lätt för alla att använda",
    "about.simplicityText": "Att skapa och hitta evenemang ska vara enkelt. Vår plattform är designad för att vara intuitiv, tillgänglig och välkomnande för alla användare.",
    "about.qualityTitle": "Kvalitet & Förtroende",
    "about.qualitySubtitle": "Tillförlitlig eventinformation",
    "about.qualityText": "Varje evenemang på vår plattform granskas för att säkerställa noggrannhet och relevans. Vi är engagerade i att upprätthålla en pålitlig källa för eventinformation.",
    "about.whatWeOfferTitle": "Vad Vi Erbjuder",
    "about.organizersTitle": "För Arrangörer",
    "about.organizersText": "Dela dina evenemang med tusentals potentiella deltagare över hela Sverige. Vår lättanvända plattform hjälper dig att nå rätt publik.",
    "about.attendeesTitle": "För Deltagare",
    "about.attendeesText": "Upptäck evenemang anpassade efter dina intressen. Filtrera efter kategori, plats, datum och mer för att hitta exakt vad du letar efter.",
    "about.verificationTitle": "Kvalitetskontroll",
    "about.verificationText": "Alla evenemang granskas för att säkerställa att de uppfyller våra kvalitetsstandarder och ger korrekt information till våra användare.",
    "about.storyTitle": "Vår Historia",
    "about.storyText1": "NowInTown startade 2025 med en vision att förändra hur människor upptäcker och delar evenemang över hela Sverige. Våra grundare, passionerade för att bygga gemenskap och kulturella upplevelser, insåg att otroliga evenemang ofta hände i människors trädgårdar utan att de visste om det.",
    "about.storyText2": "Idag är vi stolta över att tjäna eventarrangörer och deltagare över hela Sverige, från stora städer till små städer. Vår plattform har blivit en pålitlig resurs för att upptäcka allt från konstutställningar och sportevenemang till familjevänliga aktiviteter och professionella nätverksmöjligheter.",
    "about.storyText3": "Vi är engagerade i att kontinuerligt förbättra vår plattform, lägga till nya funktioner och utöka vår räckvidd för att säkerställa att inget fantastiskt evenemang förblir oupptäckt.",
    "about.coverageTitle": "Rikstäckning",
    "about.coverageText": "Evenemang från hela Sverige, från Stockholm till Kiruna",
    "about.updatesTitle": "Dagliga Uppdateringar",
    "about.updatesText": "Nya eventlistor läggs till varje dag av vår gemenskap",
    "about.communityGrowthTitle": "Växande Gemenskap",
    "about.communityGrowthText": "Tusentals eventarrangörer och deltagare litar på NowInTown",
    "about.ctaTitle": "Redo att Komma Igång?",
    "about.ctaText": "Gå med i vår gemenskap av eventarrangörer och deltagare. Skapa ditt första evenemang eller upptäck något fantastiskt som händer nära dig.",
    "about.createEvent": "Skapa ett Evenemang",
    "about.exploreEvents": "Utforska Evenemang",
    "about.contactTitle": "Kom i Kontakt",
    "about.contactText": "Har du frågor, förslag eller vill bara säga hej? Vi vill gärna höra från dig!",
    "about.contactButton": "Kontakta Oss",
    
    // Data Integrity
    "dataIntegrity.pageTitle": "Dataintegritet & Säkerhet - NowInTown | Säker Eventhantering",
    "dataIntegrity.pageDescription": "Lär dig hur NowInTown säkerställer dataintegritet och säkerhet för all eventinformation. Vårt engagemang för att skydda din data med säkerhetsåtgärder i företagsklass.",
    "dataIntegrity.title": "Dataintegritet & Säkerhet",
    "dataIntegrity.subtitle": "Ditt förtroende är vår prioritet. Vi implementerar robusta säkerhetsåtgärder för att skydda din eventdata och säkerställa dess integritet hela tiden.",
    "dataIntegrity.dataProtection": "Dataskydd",
    "dataIntegrity.dataProtectionDesc": "Säkerhet i företagsklass för din sinnesro",
    "dataIntegrity.dataProtectionText": "All eventdata är krypterad både under överföring och i vila med industristandardprotokoll. Vi använder SSL/TLS-certifikat och säker dataöverföring för att skydda din information från obehörig åtkomst.",
    "dataIntegrity.accessControl": "Åtkomstkontroll",
    "dataIntegrity.accessControlDesc": "Säker autentisering och auktorisering",
    "dataIntegrity.accessControlText1": "Eventarrangörer får unika åtkomstkoder för att hantera sina event. Endast auktoriserade användare kan visa, ändra eller radera eventinformation, vilket säkerställer fullständig kontroll över din data.",
    "dataIntegrity.accessControlText2": "Användare kan hantera sina kontoinställningar, återställa lösenord och radera sina konton när som helst genom sin",
    "dataIntegrity.accountPage": "kontosida",
    "dataIntegrity.dataIntegrity": "Dataintegritet",
    "dataIntegrity.dataIntegrityDesc": "Pålitlig och konsekvent information",
    "dataIntegrity.dataIntegrityText": "Vi upprätthåller strikta datavalideringsregler för att säkerställa att all eventinformation förblir noggrann och konsekvent. Regelbundna integritetskontroller förhindrar datakorruption och upprätthåller tillförlitlighet över vår plattform.",
    "dataIntegrity.autoCleanup": "Automatisk Rensning",
    "dataIntegrity.autoCleanupDesc": "Integritetsbaserad datahantering",
    "dataIntegrity.autoCleanupText": "Event raderas automatiskt vid slutet av deras schemalagda datum, vilket säkerställer att ingen onödig datalagring sker. Detta integritetsbaserade tillvägagångssätt minimerar datalagring och skyddar användarinformation.",
    "dataIntegrity.transparency": "Transparens",
    "dataIntegrity.transparencyDesc": "Tydliga policyer för dataanvändning",
    "dataIntegrity.transparencyText": "Vi samlar endast in väsentlig information som behövs för att visa och hantera event. Ingen personlig data delas med tredje part utan uttryckligt samtycke, och användare kan begära radering av data när som helst.",
    "dataIntegrity.regularBackups": "Regelbundna Säkerhetskopior",
    "dataIntegrity.regularBackupsDesc": "Pålitlig dataåterställning",
    "dataIntegrity.regularBackupsText": "Automatiserade säkerhetskopior säkerställer att din eventdata är säker och återställningsbar vid systemfel. Våra redundanta lagringssystem garanterar hög tillgänglighet och datahållbarhet.",
    "dataIntegrity.commitmentTitle": "Vårt Åtagande till Dig",
    "dataIntegrity.commitmentText": "På NowInTown förstår vi att din eventdata är värdefull och känslig. Vi är engagerade i att upprätthålla de högsta standarderna för datasäkerhet och integritet genom:",
    "dataIntegrity.commitmentItem1": "Regelbundna säkerhetsrevisioner och penetrationstestning",
    "dataIntegrity.commitmentItem2": "Efterlevnad av GDPR och internationella dataskyddsregler",
    "dataIntegrity.commitmentItem3": "Kontinuerlig övervakning för misstänkta aktiviteter",
    "dataIntegrity.commitmentItem4": "Snabba säkerhetsuppdateringar och patchar",
    "dataIntegrity.commitmentItem5": "Transparenta incidentrapporterings- och svarsförfaranden",
    "dataIntegrity.contactText": "Om du har några frågor om våra datasäkerhetsmetoder eller vill rapportera en säkerhetsangelägenhet, vänligen",
    "dataIntegrity.contactUs": "kontakta oss",
    "dataIntegrity.manageAccountTitle": "Hantera Ditt Konto",
    "dataIntegrity.manageAccountText": "Ta fullständig kontroll över dina kontoinställningar, uppdatera ditt lösenord eller radera ditt konto när som helst.",
    "dataIntegrity.goToAccount": "Gå till Mitt Konto",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("sv");

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
